# Generated by Django 4.2.4 on 2023-08-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='album_cover/batman.jpg', upload_to='album_cover/')),
                ('descripcion', models.TextField(default=None, max_length=500)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda_gestion.album')),
            ],
        ),
        migrations.AddField(
            model_name='cancion',
            name='generos',
            field=models.ManyToManyField(to='tienda_gestion.genero'),
        ),
    ]
