# Generated by Django 4.2.4 on 2023-08-11 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_gestion', '0002_genero_albumarte_cancion_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_gestion.artista'),
        ),
    ]
