# Generated by Django 4.2.4 on 2023-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_gestion', '0003_alter_album_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='descargas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
